spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user
          uri: lb://user-webservice
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1