spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user
          uri: lb://user-webservice
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order-webservice
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: rest
          uri: lb://product-restservice
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1