dubbo:
  scan:
    base-packages: com.haiya.service
  cloud:
    subscribed-services:
  # 这里设置名为dubbo的bean ??
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 5000
    check: false
    retries: 0
  protocol:
    name: dubbo
    port: 1${server.port}